Add mentor walkthrough notes
shiryz/pg-walkthrough pull request #17
Opened 2017-07-29 12:42 UTC by macintoshhelper

Added mentor walkthrough notes with:
- folders with intended files for each step: `walkthroughSteps`
- readme guiding mentor through the steps: `code-along-mentor-notes.md`

Database folder should be removed, and src may conflict with #16

2017-07-29 12:52 UTC, macintoshhelper commented
@ConchobarMacNessa Is it ok if I remove the database and src folder, so the newer ones will get merged in to master from the `updateForCodeAlong` branch?

They're a duplicate of step 5 anyway.

2017-07-29 13:04 UTC, ConchobarMacNessa commented
@macintoshhelper yeah no problem

2017-07-30 08:07 UTC, jsms90 requested changes
Great stuff @ConchobarMacNessa! Thanks for putting all that time in. Hopefully this will help you quite a lot with floating on day 1 and helping students :crossed_fingers: 

Just one thing about the order of the steps. I would probably create the local database before you write the connection file:
1. Navigating the initial files ([current step 1](https://github.com/foundersandcoders/pg-walkthrough/blob/mentor-walkthrough/walkthroughSteps/code-along-mentor-notes.md#step-1--navigating-the-initial-files))
1. Write the database structure & initial data ([current step 2](https://github.com/foundersandcoders/pg-walkthrough/blob/mentor-walkthrough/walkthroughSteps/code-along-mentor-notes.md#step-2--setting-up-the-database))
1. Create a local test database - make an empty database using psql and use the build file to populate it ([current Step 4](https://github.com/foundersandcoders/pg-walkthrough/blob/mentor-walkthrough/walkthroughSteps/code-along-mentor-notes.md#step-4--actually-building-and-hosting-the-database), but replace no.7 with running the `db_build.sql` file)
1. Connect the database to the server ([current step 3](https://github.com/foundersandcoders/pg-walkthrough/blob/mentor-walkthrough/walkthroughSteps/code-along-mentor-notes.md#step-3--connecting-and-building-the-database): no.1, but with a more detailed breakdown) & make a query from the server ([current Step 5](https://github.com/foundersandcoders/pg-walkthrough/blob/mentor-walkthrough/walkthroughSteps/code-along-mentor-notes.md#step-5--connecting-our-database-to-the-server))

I'm not sure whether creating a `db_build.js` ([current step 3](https://github.com/foundersandcoders/pg-walkthrough/blob/mentor-walkthrough/walkthroughSteps/code-along-mentor-notes.md#step-3--connecting-and-building-the-database): no.2) is useful / necessary in this walkthrough.

2017-07-30 08:07 UTC, jsms90 commented on walkthroughSteps/code-along-mentor-notes.md
> +1. `npm init`
If you're going to create a new repo from scratch, you need `npm init`. But if you want people to navigate existing files, they would need to clone the repo.

I'd probably pop an instruction to clone the repo straight into the readme, for students to do before the code along begins.

2017-07-30 08:07 UTC, jsms90 commented on walkthroughSteps/code-along-mentor-notes.md
> +3. run `npm run start` and navigate to `http://localhost:3000/static`. Here we see our hardcoded data from `static.js`.
Strictly speaking, you don't need "run" for `npm start` (or `npm test`). Just a nice little time saver :smile:

2017-07-30 08:07 UTC, jsms90 commented on walkthroughSteps/code-along-mentor-notes.md
> +## Step 2 – setting up the database
I would consider building, connecting & hosting to all be part of "setup"

How about
> Step 2 - Writing the schema statements and initial data

2017-07-30 08:07 UTC, jsms90 commented on walkthroughSteps/code-along-mentor-notes.md
> +  - start the file with `BEGIN;`
Needs brief explanation of transactions

2017-07-30 08:07 UTC, jsms90 commented on walkthroughSteps/code-along-mentor-notes.md
> +  - then add `DROP TABLE IF EXISTS superheroes cascade;`. This line gets drops our old database every time this file is run - i.e. every time we build our database.
Explain why we would want to do this - context: test database

2017-07-30 08:07 UTC, jsms90 commented on walkthroughSteps/code-along-mentor-notes.md
> +  - we then `COMMIT;` our database.
Students should know this is connected to BEGIN (see above)

2017-07-30 08:07 UTC, jsms90 commented on walkthroughSteps/code-along-mentor-notes.md
> +  - For this we require the modules `pg` and `env2`, so `npm install --save pg env2` and require them at the top of this file.
Explanation of what the `pg` module is: https://github.com/brianc/node-postgres

2017-07-30 08:07 UTC, jsms90 commented on walkthroughSteps/code-along-mentor-notes.md
> +## Step 4 – actually building and hosting the database
Just "building". We don't host the database in this walkthrough

2017-07-30 08:07 UTC, jsms90 commented on walkthroughSteps/code-along-mentor-notes.md
> +4. Create a superuser with a password by typing `CREATE USER [the new username] WITH SUPERUSER PASSWORD '[the password of the database]'`; (the password needs to be in quotes, otherwise you get an er
Needs explanation of why this is necessary

2017-07-30 08:07 UTC, jsms90 commented on walkthroughSteps/code-along-mentor-notes.md
> +7. Connect to the database by typing `psql postgres://[username]:[password]@localhost:5432/[database]` and test if everything worked by typing `SELECT * FROM superheroes;`. You should see the data we
I think it's just [`psql DBNAME USERNAME`](https://www.postgresql.org/docs/9.3/static/app-psql.html) and that you don't need the whole `postgres://[username]:[password]@localhost:5432/[database]` ?

2017-07-30 08:07 UTC, jsms90 commented on walkthroughSteps/code-along-mentor-notes.md
> +1. Our database is now outlined, but we need a way to connect it. Inside the `/database` folder, create a file called `db_connection.js`.
This is really the meatiest part of the walkthrough, where the `pg` module itself is going to be explained:
+ Explanation of what a pool of client connections is (i.e. `pg.Pool`) while typing [this line](https://github.com/foundersandcoders/pg-walkthrough/blob/mentor-walkthrough/walkthroughSteps/step-5/database/db_connection.js#L1)
+ What's happening [here](https://github.com/foundersandcoders/pg-walkthrough/blob/mentor-walkthrough/walkthroughSteps/step-5/database/db_connection.js#L5) - hopefully they should understand the concept of environment variables by this point. But it's still worth clarifying.
+ Ensure students understand that the environment variable is being used for [username & password](https://github.com/foundersandcoders/pg-walkthrough/blob/mentor-walkthrough/walkthroughSteps/step-5/database/db_connection.js#L15-L16) and [database](https://github.com/foundersandcoders/pg-walkthrough/blob/mentor-walkthrough/walkthroughSteps/step-5/database/db_connection.js#L13) in the pool configuration options.
+ Explain why they need [to require in `url`](https://github.com/foundersandcoders/pg-walkthrough/blob/mentor-walkthrough/walkthroughSteps/step-5/database/db_connection.js#L2) i.e. how it's being used [on these lines](https://github.com/foundersandcoders/pg-walkthrough/blob/mentor-walkthrough/walkthroughSteps/step-5/database/db_connection.js#L7-L8) to take the username and password from the `DB_URL` environment variable
+ Explain what it means to [set up a new pool of clients](https://github.com/foundersandcoders/pg-walkthrough/blob/mentor-walkthrough/walkthroughSteps/step-5/database/db_connection.js#L21)
+ Use the `pg` documentation (?) to explain how students should know what configuration options it takes
+ Explain what difference the [number of connections](https://github.com/foundersandcoders/pg-walkthrough/blob/mentor-walkthrough/walkthroughSteps/step-5/database/db_connection.js#L14) makes
+ Make 100% sure students understand ES6 destructuring where it is used in `{ Pool }` and `[username, password]`

2017-07-30 08:07 UTC, jsms90 commented on walkthroughSteps/code-along-mentor-notes.md
> +2. We also need a way of building our database. In the `/database` folder, create a file called `db_build.js`.
Explain why we are writing this and when & how it would be used.

2017-07-30 08:07 UTC, jsms90 commented on walkthroughSteps/code-along-mentor-notes.md
> +## Step 5 – connecting our database to the server
Slightly pedantic but: connecting _to_ our database _from_ the server

2017-07-30 08:13 UTC, shiryz commented on walkthroughSteps/step-1/database/db_connection.js
> +/* require('env2')('../config.env'); =
I would move this comment to the mentor notes.

2017-07-30 08:51 UTC, shiryz requested changes
Some comments apply to the same file in a different step, make sure it's applied to all of them :smile:

2017-07-30 08:51 UTC, shiryz commented on README.md
>  Inspired by [Matthew Glover](https://github.com/matthewglover) and his awesome [pg-app](https://github.com/matthewglover/pg-app/blob/master/get_pups.js)
Change the link to the repo itself, wait for #16 to be merged.

2017-07-30 08:51 UTC, shiryz commented on walkthroughSteps/code-along-mentor-notes.md
> +  - then add `DROP TABLE IF EXISTS superheroes cascade;`. This line gets drops our old database every time this file is run - i.e. every time we build our database.
I would add that you should explain this would never be done in a real project because you will not start the database from scratch every time.

2017-07-30 08:51 UTC, shiryz commented on walkthroughSteps/code-along-mentor-notes.md
> +7. Connect to the database by typing `psql postgres://[username]:[password]@localhost:5432/[database]` and test if everything worked by typing `SELECT * FROM superheroes;`. You should see the data we
something less important, this is 8 not 7

2017-07-30 08:51 UTC, shiryz commented on walkthroughSteps/step-2/database/db_build.sql
> +CREATE TABLE superheroes (
I would add an entry that'll have a default so you can show how it works.

2017-07-30 08:51 UTC, shiryz commented on walkthroughSteps/step-3/database/db_connection.js
> -/* require('env2')('../config.env'); =
Should be added to the mentor's notes, would explain this is syntactic sugar and is only an abbreviation to the 2 lines you usually use.

2017-07-30 08:51 UTC, shiryz commented on walkthroughSteps/step-3/database/db_connection0.js
> +options.ssl = (options.host !== 'localhost');
move into options and use `params.hostname` instead of `options.host`

2017-07-30 09:37 UTC, jsms90 commented on walkthroughSteps/code-along-mentor-notes.md
> +  - then add `DROP TABLE IF EXISTS superheroes cascade;`. This line gets drops our old database every time this file is run - i.e. every time we build our database.
For the hosted database, this is essentially just an initialisation file.. You run it once, when you first set up the database. But yes, you never never want to use this file again on the hosted version, because it would wipe your hosted database.

But on your test database, you could run this file to wipe the it before executing your test suite.

Otherwise, what's the point in creating a `db_build.js`? My understanding was that you can then create a build script (`build: node database/db_build.js`) and do `npm run build` before then running your test suite.

2017-07-31 15:46 UTC, macintoshhelper commented
@shiryz I've gone through your requested changes and made them.

2017-07-31 16:48 UTC, macintoshhelper commented on walkthroughSteps/code-along-mentor-notes.md
> +7. Connect to the database by typing `psql postgres://[username]:[password]@localhost:5432/[database]` and test if everything worked by typing `SELECT * FROM superheroes;`. You should see the data we
It might be good having it as a URL so the password and port are tested.

2017-07-31 16:54 UTC, macintoshhelper commented on walkthroughSteps/code-along-mentor-notes.md
> +1. `npm init`
Added a `Getting Started` section

2017-07-31 16:54 UTC, macintoshhelper commented on walkthroughSteps/code-along-mentor-notes.md
> +3. run `npm run start` and navigate to `http://localhost:3000/static`. Here we see our hardcoded data from `static.js`.
Changed to `npm start`

2017-07-31 16:55 UTC, macintoshhelper commented on walkthroughSteps/code-along-mentor-notes.md
> +## Step 2 – setting up the database
Done

2017-07-31 16:56 UTC, macintoshhelper commented on walkthroughSteps/code-along-mentor-notes.md
> +  - start the file with `BEGIN;`
I've added a mention of transactions here.

2017-07-31 17:01 UTC, macintoshhelper commented on walkthroughSteps/code-along-mentor-notes.md
> +  - then add `DROP TABLE IF EXISTS superheroes cascade;`. This line gets drops our old database every time this file is run - i.e. every time we build our database.
I've added an explanation here.

2017-07-31 17:01 UTC, macintoshhelper commented on walkthroughSteps/code-along-mentor-notes.md
> +1. Our database is now outlined, but we need a way to connect it. Inside the `/database` folder, create a file called `db_connection.js`.
I've done these.

2017-07-31 17:03 UTC, macintoshhelper commented
I think I've made all of the requested changes.

2017-07-31 18:49 UTC, shiryz approved these changes

2017-07-31 22:58 UTC, jsms90 commented
@macintoshhelper please merge with master tomorrow, now that PR #16 has been merged

2017-08-01 12:13 UTC, macintoshhelper commented
@jsms90 I've fixed the merge conflicts. I'm creating a new branch for refactoring.

2017-08-01 15:18 UTC, jsms90 approved these changes

2017-08-01 15:18 UTC, merged