Mentor walkthrough refactor [merge mentor-walkthrough first]
shiryz/pg-walkthrough pull request #20
Opened 2017-08-01 14:47 UTC by macintoshhelper

Fixes #19 by inlining code in mentor notes. Should make it easier for mentors to reproduce the walkthrough and explain everything better, while having the code ready.

Merge `mentor-walkthrough` first

2017-08-07 09:07 UTC, shiryz requested changes
Nothing major it's pretty great :sparkles:

2017-08-07 09:07 UTC, shiryz commented on walkthroughSteps/code-along-mentor-notes.md
> +    2. Write `DROP TABLE IF EXISTS superheroes cascade;`.
cascade is a sql key word, better capitalized.

2017-08-07 09:07 UTC, shiryz commented on walkthroughSteps/code-along-mentor-notes.md
> +        - All tables should have an integer `id` that is set as a `PRIMARY KEY` - this is used relate databased together (integer PRIMARY KEY helps with performance)
Can you add a note that primary key is the combination of UNIQUE and NOT NULL

2017-08-07 09:07 UTC, shiryz commented on walkthroughSteps/code-along-mentor-notes.md
> +    - `ssl` will enable SSL (set to true) if you're not testing on a local machine.
Add that SSL (or secure sockets layer) when set to true ensures you are connecting to the database from a secure server (https)

2017-08-07 10:01 UTC, macintoshhelper commented
@shiryz I've made the requested changes 👍

2017-08-07 11:15 UTC, shiryz approved these changes
Wicked!

2017-09-25 20:57 UTC, eliasmalik approved these changes

2017-09-25 20:57 UTC, merged